sonar.organization=codefactory-20261-eap05
sonar.projectKey=CodeFactory-20261-EAP05_banco-digital-backend
sonar.projectName=banco-digital-backend
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=21
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
