spring.application.name=backend

# Conexion Neon (defaults entregados por el equipo)
spring.datasource.url=${NEON_DB_URL:jdbc:postgresql://ep-green-smoke-ai21o0uf-pooler.c-4.us-east-1.aws.neon.tech:5432/bancodigital?sslmode=require}
spring.datasource.username=${NEON_DB_USER:neondb_owner}
spring.datasource.password=${NEON_DB_PASSWORD:npg_7qIHY9oGTSLM}

# Hibernate + Migraciones
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# Puerto del servidor
server.port=8080